// <auto-generated />
using System;
using DiplomaManagementSystem.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DiplomaManagementSystem.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DiplomaManagementSystem.Application.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<short?>("AcademicRank")
                        .HasColumnType("smallint");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DefenceSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("ShortDisplayName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("StudyGroupId")
                        .HasColumnType("uuid");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<short>("UserKind")
                        .HasColumnType("smallint");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("DefenceSessionId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("StudyGroupId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.AnnualRoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DefenceSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<short>("RoleType")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("DefenceSessionId", "RoleType")
                        .IsUnique();

                    b.ToTable("annual_role_assignments", (string)null);
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("DefenceSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NewValue")
                        .HasColumnType("text");

                    b.Property<string>("OldValue")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("PerformedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PerformedById")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DefenceSessionId");

                    b.HasIndex("PerformedAt");

                    b.HasIndex("PerformedById");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.DefenceDateOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("DefenceSessionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DefenceSessionId", "Date")
                        .IsUnique();

                    b.ToTable("defence_date_options", (string)null);
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.DefenceDatePreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DefenceDateOptionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DiplomaId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("RequesterType")
                        .HasColumnType("smallint");

                    b.Property<Guid>("RequesterUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DefenceDateOptionId");

                    b.HasIndex("DiplomaId")
                        .IsUnique();

                    b.HasIndex("RequesterUserId");

                    b.ToTable("defence_date_preferences", (string)null);
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.DefenceSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Semester")
                        .HasColumnType("integer");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<short>("Type")
                        .HasColumnType("smallint");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("defence_sessions", (string)null);
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.DefenceSessionMilestone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DefenceSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<int>("ExpectedPercent")
                        .HasColumnType("integer");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DefenceSessionId", "DueDate")
                        .IsUnique();

                    b.HasIndex("DefenceSessionId", "Ordinal")
                        .IsUnique();

                    b.ToTable("defence_session_milestones", null, t =>
                        {
                            t.HasCheckConstraint("CK_defence_session_milestones_expected_percent", "\"ExpectedPercent\" >= 0 AND \"ExpectedPercent\" <= 100");

                            t.HasCheckConstraint("CK_defence_session_milestones_ordinal", "\"Ordinal\" >= 1 AND \"Ordinal\" <= 3");
                        });
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FacultyId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("FacultyId", "Name")
                        .IsUnique();

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.DepartmentAdminAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("DepartmentId", "UserId")
                        .IsUnique();

                    b.ToTable("department_admin_assignments", (string)null);
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.DepartmentEmployee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<short?>("AcademicRank")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ShortDisplayName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("DepartmentId", "UserId")
                        .IsUnique();

                    b.ToTable("department_employees", (string)null);
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.Diploma", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<short>("AdmissionStatus")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short?>("CurrentAdmissionStep")
                        .HasColumnType("smallint");

                    b.Property<DateOnly?>("DefenceDate")
                        .HasColumnType("date");

                    b.Property<Guid>("DefenceSessionId")
                        .HasColumnType("uuid");

                    b.Property<short>("LifecycleStatus")
                        .HasColumnType("smallint");

                    b.Property<short>("ReviewAssignmentStatus")
                        .HasColumnType("smallint");

                    b.Property<Guid?>("ReviewerId")
                        .HasColumnType("uuid");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageFolderId")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<short>("SupervisorAssignmentStatus")
                        .HasColumnType("smallint");

                    b.Property<Guid?>("SupervisorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CurrentAdmissionStep");

                    b.HasIndex("DefenceSessionId");

                    b.HasIndex("ReviewerId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SupervisorId");

                    b.HasIndex("StudentId", "DefenceSessionId")
                        .IsUnique();

                    b.ToTable("diplomas", (string)null);
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.DiplomaAdmissionStepAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("DiplomaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSecretaryOverride")
                        .HasColumnType("boolean");

                    b.Property<short>("Outcome")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecordedById")
                        .HasColumnType("uuid");

                    b.Property<short>("Step")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("DiplomaId");

                    b.HasIndex("RecordedById");

                    b.HasIndex("DiplomaId", "Step", "AttemptNumber")
                        .IsUnique();

                    b.ToTable("diploma_admission_step_attempts", null, t =>
                        {
                            t.HasCheckConstraint("CK_diploma_admission_step_attempts_outcome", "\"Outcome\" IN (0, 1)");
                        });
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.DiplomaComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DiplomaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("DiplomaId");

                    b.ToTable("diploma_comments", (string)null);
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.DiplomaDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AdmissionStepAttemptId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DiplomaId")
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("character varying(260)");

                    b.Property<short>("Kind")
                        .HasColumnType("smallint");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageFileId")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UploadedById")
                        .HasColumnType("uuid");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdmissionStepAttemptId");

                    b.HasIndex("DiplomaId");

                    b.HasIndex("UploadedById");

                    b.HasIndex("DiplomaId", "Kind", "VersionNumber")
                        .IsUnique();

                    b.ToTable("diploma_documents", (string)null);
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.DiplomaMilestoneProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActualPercent")
                        .HasColumnType("integer");

                    b.Property<Guid>("DiplomaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MilestoneId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RecordedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MilestoneId");

                    b.HasIndex("RecordedByUserId");

                    b.HasIndex("DiplomaId", "MilestoneId")
                        .IsUnique();

                    b.ToTable("diploma_milestone_progress", null, t =>
                        {
                            t.HasCheckConstraint("CK_diploma_milestone_progress_actual_percent", "\"ActualPercent\" >= 0 AND \"ActualPercent\" <= 100");
                        });
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.DiplomaTopicVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DiplomaId")
                        .HasColumnType("uuid");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedById")
                        .HasColumnType("uuid");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("SupervisorReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SupervisorReviewedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DiplomaId");

                    b.HasIndex("ReviewedById");

                    b.HasIndex("SupervisorReviewedById");

                    b.HasIndex("DiplomaId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("diploma_topic_versions", (string)null);
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.EmployeeSessionWorkloadLimit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DefenceSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<int?>("MaxReviewerStudents")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxSupervisorStudents")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("DefenceSessionId", "EmployeeId")
                        .IsUnique();

                    b.ToTable("employee_session_workload_limits", (string)null);
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.ExaminationCommissionParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DefenceSessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<short>("Role")
                        .HasColumnType("smallint");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DefenceSessionId")
                        .IsUnique()
                        .HasFilter("\"Role\" = 0");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("DefenceSessionId", "EmployeeId")
                        .IsUnique()
                        .HasFilter("\"EmployeeId\" IS NOT NULL");

                    b.HasIndex("DefenceSessionId", "Role");

                    b.ToTable("examination_commission_participants", (string)null);
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.Faculty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("faculties", (string)null);
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.Specialty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId", "Code")
                        .IsUnique();

                    b.ToTable("specialties", (string)null);
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.StudyGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Course")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DefenceSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("SpecialtyId")
                        .HasColumnType("uuid");

                    b.Property<string>("StudyForm")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("DefenceSessionId");

                    b.HasIndex("SpecialtyId");

                    b.HasIndex("DefenceSessionId", "Name")
                        .IsUnique();

                    b.ToTable("study_groups", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DiplomaManagementSystem.Application.Identity.ApplicationUser", b =>
                {
                    b.HasOne("DiplomaManagementSystem.Domain.Entities.DefenceSession", "DefenceSession")
                        .WithMany()
                        .HasForeignKey("DefenceSessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DiplomaManagementSystem.Domain.Entities.StudyGroup", "StudyGroup")
                        .WithMany()
                        .HasForeignKey("StudyGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DefenceSession");

                    b.Navigation("StudyGroup");
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.AnnualRoleAssignment", b =>
                {
                    b.HasOne("DiplomaManagementSystem.Domain.Entities.DefenceSession", "DefenceSession")
                        .WithMany("RoleAssignments")
                        .HasForeignKey("DefenceSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiplomaManagementSystem.Application.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DefenceSession");
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("DiplomaManagementSystem.Domain.Entities.DefenceSession", "DefenceSession")
                        .WithMany()
                        .HasForeignKey("DefenceSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DiplomaManagementSystem.Application.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("PerformedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DefenceSession");
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.DefenceDateOption", b =>
                {
                    b.HasOne("DiplomaManagementSystem.Domain.Entities.DefenceSession", "DefenceSession")
                        .WithMany("DefenceDateOptions")
                        .HasForeignKey("DefenceSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DefenceSession");
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.DefenceDatePreference", b =>
                {
                    b.HasOne("DiplomaManagementSystem.Domain.Entities.DefenceDateOption", "DefenceDateOption")
                        .WithMany("Preferences")
                        .HasForeignKey("DefenceDateOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiplomaManagementSystem.Domain.Entities.Diploma", "Diploma")
                        .WithOne("DefenceDatePreference")
                        .HasForeignKey("DiplomaManagementSystem.Domain.Entities.DefenceDatePreference", "DiplomaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiplomaManagementSystem.Application.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("RequesterUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DefenceDateOption");

                    b.Navigation("Diploma");
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.DefenceSession", b =>
                {
                    b.HasOne("DiplomaManagementSystem.Domain.Entities.Department", "Department")
                        .WithMany("DefenceSessions")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.DefenceSessionMilestone", b =>
                {
                    b.HasOne("DiplomaManagementSystem.Domain.Entities.DefenceSession", "DefenceSession")
                        .WithMany("Milestones")
                        .HasForeignKey("DefenceSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DefenceSession");
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.Department", b =>
                {
                    b.HasOne("DiplomaManagementSystem.Domain.Entities.Faculty", "Faculty")
                        .WithMany("Departments")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.DepartmentAdminAssignment", b =>
                {
                    b.HasOne("DiplomaManagementSystem.Domain.Entities.Department", "Department")
                        .WithMany("AdminAssignments")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiplomaManagementSystem.Application.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.DepartmentEmployee", b =>
                {
                    b.HasOne("DiplomaManagementSystem.Domain.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiplomaManagementSystem.Application.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.Diploma", b =>
                {
                    b.HasOne("DiplomaManagementSystem.Domain.Entities.DefenceSession", "DefenceSession")
                        .WithMany("Diplomas")
                        .HasForeignKey("DefenceSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiplomaManagementSystem.Application.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DiplomaManagementSystem.Application.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiplomaManagementSystem.Application.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DefenceSession");
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.DiplomaAdmissionStepAttempt", b =>
                {
                    b.HasOne("DiplomaManagementSystem.Domain.Entities.Diploma", "Diploma")
                        .WithMany("AdmissionStepAttempts")
                        .HasForeignKey("DiplomaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiplomaManagementSystem.Application.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("RecordedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Diploma");
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.DiplomaComment", b =>
                {
                    b.HasOne("DiplomaManagementSystem.Application.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiplomaManagementSystem.Domain.Entities.Diploma", "Diploma")
                        .WithMany("Comments")
                        .HasForeignKey("DiplomaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Diploma");
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.DiplomaDocument", b =>
                {
                    b.HasOne("DiplomaManagementSystem.Domain.Entities.DiplomaAdmissionStepAttempt", "AdmissionStepAttempt")
                        .WithMany()
                        .HasForeignKey("AdmissionStepAttemptId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DiplomaManagementSystem.Domain.Entities.Diploma", "Diploma")
                        .WithMany("Documents")
                        .HasForeignKey("DiplomaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiplomaManagementSystem.Application.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AdmissionStepAttempt");

                    b.Navigation("Diploma");
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.DiplomaMilestoneProgress", b =>
                {
                    b.HasOne("DiplomaManagementSystem.Domain.Entities.Diploma", "Diploma")
                        .WithMany("MilestoneProgressEntries")
                        .HasForeignKey("DiplomaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiplomaManagementSystem.Domain.Entities.DefenceSessionMilestone", "Milestone")
                        .WithMany("ProgressEntries")
                        .HasForeignKey("MilestoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiplomaManagementSystem.Application.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("RecordedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Diploma");

                    b.Navigation("Milestone");
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.DiplomaTopicVersion", b =>
                {
                    b.HasOne("DiplomaManagementSystem.Domain.Entities.Diploma", "Diploma")
                        .WithMany("TopicVersions")
                        .HasForeignKey("DiplomaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiplomaManagementSystem.Application.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ReviewedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DiplomaManagementSystem.Application.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("SupervisorReviewedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Diploma");
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.EmployeeSessionWorkloadLimit", b =>
                {
                    b.HasOne("DiplomaManagementSystem.Domain.Entities.DefenceSession", "DefenceSession")
                        .WithMany()
                        .HasForeignKey("DefenceSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiplomaManagementSystem.Application.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DefenceSession");
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.ExaminationCommissionParticipant", b =>
                {
                    b.HasOne("DiplomaManagementSystem.Domain.Entities.DefenceSession", "DefenceSession")
                        .WithMany("ExaminationCommissionParticipants")
                        .HasForeignKey("DefenceSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiplomaManagementSystem.Application.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DefenceSession");
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.Specialty", b =>
                {
                    b.HasOne("DiplomaManagementSystem.Domain.Entities.Department", "Department")
                        .WithMany("Specialties")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.StudyGroup", b =>
                {
                    b.HasOne("DiplomaManagementSystem.Domain.Entities.DefenceSession", "DefenceSession")
                        .WithMany("StudyGroups")
                        .HasForeignKey("DefenceSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DiplomaManagementSystem.Domain.Entities.Specialty", "Specialty")
                        .WithMany("StudyGroups")
                        .HasForeignKey("SpecialtyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DefenceSession");

                    b.Navigation("Specialty");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("DiplomaManagementSystem.Application.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("DiplomaManagementSystem.Application.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DiplomaManagementSystem.Application.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("DiplomaManagementSystem.Application.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.DefenceDateOption", b =>
                {
                    b.Navigation("Preferences");
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.DefenceSession", b =>
                {
                    b.Navigation("DefenceDateOptions");

                    b.Navigation("Diplomas");

                    b.Navigation("ExaminationCommissionParticipants");

                    b.Navigation("Milestones");

                    b.Navigation("RoleAssignments");

                    b.Navigation("StudyGroups");
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.DefenceSessionMilestone", b =>
                {
                    b.Navigation("ProgressEntries");
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.Department", b =>
                {
                    b.Navigation("AdminAssignments");

                    b.Navigation("DefenceSessions");

                    b.Navigation("Employees");

                    b.Navigation("Specialties");
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.Diploma", b =>
                {
                    b.Navigation("AdmissionStepAttempts");

                    b.Navigation("Comments");

                    b.Navigation("DefenceDatePreference");

                    b.Navigation("Documents");

                    b.Navigation("MilestoneProgressEntries");

                    b.Navigation("TopicVersions");
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.Faculty", b =>
                {
                    b.Navigation("Departments");
                });

            modelBuilder.Entity("DiplomaManagementSystem.Domain.Entities.Specialty", b =>
                {
                    b.Navigation("StudyGroups");
                });
#pragma warning restore 612, 618
        }
    }
}
